[WIP] Pushing cypress part of challenges
led13714/hacker-challenge-qa-automation pull request #3
Opened 2023-12-01 15:21 UTC by HasanRamiz

2023-12-04 12:30 UTC, led13714 requested changes
a couple of things I noted aside from my other comments:

- you used a lot of xpath expressions as locators, is that necessary?
- package.json in cypress directory is missing. how to execute tests?
- maybe update readme on root directory with regards to cypress

2023-12-04 12:30 UTC, led13714 commented on cypress/fixtures/example.json
> +}
file can be removed

2023-12-04 12:30 UTC, led13714 commented on .gitignore
> +*.DS_Store
please add new lines at the end of a file (everywhere)

2023-12-04 12:30 UTC, led13714 commented on cypress/page-objects/fifth_challenge.js
> +            //cy.get('input.hidden-password').type(value);
remove dead code

2023-12-04 12:30 UTC, led13714 commented on cypress/integration/challenges.spec.js
> +        finalpage.restartButton()
clicking restart seems obsolete to me when it comes to finalizing all 10 challenges

2023-12-04 12:30 UTC, led13714 commented on cypress/integration/challenges.spec.js
> +        ninthpage.enterPasswordAndClick()
I think it would be good to make the image visible in order to mimic real user behavior before entering pw and submitting it

2023-12-04 12:30 UTC, led13714 commented on cypress/page-objects/seventh_challenge.js
> +    // it's a limitation, already tried stubs & spies and also javascript code but it always returned
take a look at my solution with pure JS - I managed to capture the log and read the pw from it.

2023-12-04 12:30 UTC, led13714 commented on cypress/page-objects/sixth_challenge.js
> +           //cy.get('#inputField').should('have.value', value);
method is unused? can be removed

2023-12-04 12:30 UTC, led13714 commented on cypress/integration/challenges.spec.js
> +        fifthpage.updateURL()
why wasn't it working separated? take a look at my solution on how to update href attribute of button, then you can click that button and don't have to use `cy.visit()` to stay closer to real user behavior

2023-12-04 12:30 UTC, led13714 commented on cypress/page-objects/eighth_challenge.js
> +    validateChallengeFifthHeading() {
`validateChallengeFifthHeading ` has been used in many page-object classes. I think this is a copy&paste error.
Please rename it according to the classes

2023-12-04 12:30 UTC, led13714 commented on cypress/page-objects/tenth_challenge.js
> +          cy.get('.network-btn').click()
I think this `click()` should be moved in a separate method as this has nothing to do with `getPasswordFromNetworkRequest `

2023-12-04 16:38 UTC, HasanRamiz commented on cypress/page-objects/seventh_challenge.js
> +    // it's a limitation, already tried stubs & spies and also javascript code but it always returned
let's discuss it tomorrow, as I also tried your solution other than using all available cypress ones but didn't get any success in extracting/reading the value.

2023-12-05 07:33 UTC, led13714 requested changes

2023-12-05 07:33 UTC, led13714 commented on .github/workflows/cypress_test.yml
> +on: [push]
```suggestion
workflow_dispatch:
pull_request:
    branches: [main]
```

2023-12-05 07:33 UTC, led13714 commented on .github/workflows/cypress_test.yml
> +on: [push]
`workflow_dispatch` will allow manual pipeline execution

2023-12-05 07:33 UTC, led13714 commented on .github/workflows/cypress_test.yml
> +on: [push]
other than that running on PRs should be enough

2023-12-05 07:33 UTC, led13714 commented on README.md
> +    npm run cypress-headedless          # run all tests on electron headlessly
```suggestion
    npm run cypress-headless          # run all tests on electron headlessly
```

2023-12-05 07:33 UTC, led13714 commented on .github/workflows/cypress_test.yml
> +          command: npm run cypress-headless
can you execute tests in chrome headless so that the pipelines are comparable?
(Playwright tests run in chrome in Github workflow)

2023-12-05 07:33 UTC, led13714 commented on cypress/fixtures/example.json
> +}
this file is still there

2023-12-05 07:33 UTC, led13714 commented on cypress/page-objects/eighth_challenge.js
> +}
new line at the end of files 🍤

2023-12-05 07:33 UTC, led13714 commented on cypress/page-objects/eighth_challenge.js
> +}
everywhere^^

2023-12-05 07:33 UTC, led13714 commented on package.json
> +{
this file should be inside the /cypress directory to separate outer python backend from playwright's and cypress' dependencies

2023-12-05 07:33 UTC, led13714 commented on cypress/page-objects/tenth_challenge.js
> +        cy.request('https://hacker-challenge.netlify.app//challenges/normal/jellyfish-password.json').then(
general note: I think you should run the tests against a localhost hosted version of the hacker challenge to be less dependent and increase speed

2023-12-05 07:35 UTC, led13714 commented on .github/workflows/cypress_test.yml
> +      # Install npm dependencies, cache them correctly
you missed to install dependencies:
`      - name: Install dependencies
        run: npm ci`

2023-12-05 07:37 UTC, led13714 requested changes

2023-12-05 07:37 UTC, led13714 commented on .github/workflows/cypress_test.yml
> +          command: npm run cypress-headless
what about test reporting and saving it to the executed workflow job?

2023-12-05 07:37 UTC, led13714 commented on .github/workflows/cypress_test.yml
> +    name: Headless Tests
```suggestion
    name: Cypress Tests
```

2023-12-05 07:37 UTC, led13714 commented on .github/workflows/cypress_test.yml
> +    runs-on: ubuntu-22.04
```suggestion
    runs-on: ubuntu-22.04
        defaults:
      run:
        working-directory: cypress
```

this requires you to move the package.json to /cypress directory

2023-12-05 10:41 UTC, led13714 approved these changes

2023-12-05 14:27 UTC, merged